### ISSUE TITLE
Text for "Adjust Font Size" in white

### ISSUE THREAD

**Issue by carywalski** [bennyluk/Sienna-Accessibility-Widget#2]
It's meee again! Hopefully with another simple fix. I just added the widget to a website where the very top of the website has a font that's in white. I don't know if that fact is causing the issue, but when I open the widget, the "Adjust Font Size" area is also in white. Thanks for taking a look!

![image](https://user-images.githubusercontent.com/23343768/204840175-52d1cc97-f3c2-46b1-a900-309b4dbc6815.png)

https://cornet-flounder-dd2y.squarespace.com/new
Password: unity

**Comment by bennyluk** [comment]
The issue is resolved.

**Comment by carywalski** [comment]
Thanks! :)

*Cary Walski*
*Founder & nerd-in-chief*

612.724.1655 | ***@***.*** | Schedule a Meeting
<https://calendly.com/cary-walski/30min>
She/Her/Hers


Copilot: Where could you go with a Copilot? <http://gocopilot.org>
Web + Social + Creative for Nonprofits
