### ISSUE TITLE
OpenDyslexic Font does not work without local installation

### ISSUE THREAD

**Issue by benjisoft** [bennyluk/Sienna-Accessibility-Widget#6]
I'm not sure what I'm doing wrong. I've tried including OpenDyslexic from a CDN & installing OD in WebFlow. I just cannot get it to work. It falls back to Comic Sans. Am I missing something?

**Comment by benjisoft** [comment]
Live site is https://visimedia.co.uk

**Comment by benjisoft** [comment]
Update: It's worked but only when OD is installed locally. Is there a way of using OD as a webfont?

**Comment by bennyluk** [comment]
Fixed bug that was causing issues when loading the dyslexic font on certain browsers. Commit: 5b3ac5b14145ba5f2df8ca1bcfa3aacb1881b20d
